language: go

go:
  - 1.6
  - tip

env:
  - GIMME_OS=linux GIMME_ARCH=amd64
  - GIMME_OS=linux GIMME_ARCH=arm
  - GIMME_OS=linux GIMME_ARCH=arm64
  - GIMME_OS=darwin GIMME_ARCH=amd64
  - GIMME_OS=windows GIMME_ARCH=amd64
  - GIMME_OS=windows GIMME_ARCH=386

install:
  - bin/setup

script:
  - go build -v ./cmd/dphx

after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
