[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/armon/go-socks5"
  revision = "e75332964ef517daa070d7c38a9466a0d687e0a5"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "golang.org/x/crypto"
  revision = "0e37d006457bf46f9e6692014ba72ef82c33022c"

[[constraint]]
  name = "golang.org/x/net"
  revision = "f04abc6bdfa7a0171a8a0c9fd2ada9391044d056"
